# 
# VERSION CHANGES
#

BV=$(shell (git rev-list HEAD --count))
BD=$(shell (date))
CFLAGS=-O -DBUILD_VER="$(BV)" -DBUILD_DATE=\""$(BD)"\" -DFAKE_SERIAL=$(FAKE_SERIAL)
LIBS=
CC=gcc
GCC=g++

OBJ=bside-adm20

default: $(OBJ)
	@echo
	@echo

bside-adm20: bside-adm20-linux.cpp
	@echo Build Release $(BV)
	@echo Build Date $(BD)
	${GCC} ${CFLAGS} $(COMPONENTS) bside-adm20-linux.cpp ${OFILES} -o ${OBJ}

clean:
	del /s ${OBJ} ${WINOBJ}
